### ISSUE TITLE
Notification is not sending when textarea for custom message is not used

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#105]
this issue  exist in released and latest versions
![image](https://cloud.githubusercontent.com/assets/5111163/25050784/0a16a6dc-2152-11e7-8017-89bb3ee6794b.png)

notify user - https://usabilitydynamics.uservoice.com/admin/tickets/13975?tracking_code=3849114b6761a017b838665eb8757f62

**Comment by alimuzzaman** [comment]
@Mashenka 
> Display textarea for custom message.

This enable or disable message field in Fields list (Right side).

You can't send empty message unless you have allow it by "**Send message notification even if no message is submitted.**"

There nothing wrong with this field, this is just an unneeded field. This just increase hassle. We can simply enable message field by default. There no of this field.

**Comment by Mashenka** [comment]
@alimuzzaman I meant notification is not sending without that field.

**Comment by Mashenka** [comment]
still not sending - https://workspace.uds.io/crm/
