### ISSUE TITLE
Default request method of forms

### ISSUE THREAD

**Issue by felipeelia** [wp-crm/wp-crm#129]
Hi!

Is there a way to change the default request method of a shortcode form? Nowadays it seems to be set with this code at `lib/class_contact_messages.php:655`:

```
    $form = wp_parse_args( $wp_crm[ 'wp_crm_contact_system_data' ][ $form_slug ], array(
      'request_method' => 'GET',
    ) );
```

But GET has a default limitation of input length... so wouldn't be better have a POST there? Or there is another way (a config, a filter or something) to change that?

Thanks!

**Comment by Mashenka** [comment]
Thank you for your question. We had an option before to choose that. We will revert that option in the next release
You can do this right now

![image](https://user-images.githubusercontent.com/5111163/31774969-ee3f747a-b4ef-11e7-8804-e7b3dffcf0c4.png)
