### ISSUE TITLE
File Upload field error when sending form

### ISSUE THREAD

**Issue by paugnu** [wp-crm/wp-crm#138]
Hi,

-At least in Firefox- After adding a new 'file upload' field, when I click on 'Browse files', the form is sent (instead of showing the upload file browse window). The problem is that 'event is not defined'.

I'm correcting this from my fork.

**Comment by Mashenka** [comment]
Thank you for pointing to the issue. We will check and let you know.

**Comment by Mashenka** [comment]
@SoSeductive here is the link - https://workspace.uds.io/crm/

**Comment by Mashenka** [comment]
@PauGNU Hello

We have tested the issue. It can't be replicated on latest versions of wp-crm, WP, Mozilla, Chrome. However, you commit may have sense in older browsers. We will add your commit to the next release.

Regards.
