### ISSUE TITLE
Number of rows per page not working and breaks that in other plugins

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#151]
Here we can see a function which works not correct and crashed wp-property plugin function
https://github.com/wp-crm/wp-crm/blob/v1.0/lib/class_functions.php#L2862

https://github.com/wp-property/wp-property/issues/538#issuecomment-379194731

also found that issue created long time ago - https://github.com/wp-crm/wp-crm/issues/11

**Comment by SoSeductive** [comment]
@Mashenka Done. Issue with pagination in CRM which crashed property list pagination was resolved
* Removed pagination from CRM user list page
* Fix pagination function for messages on user page, which crashed property list pagination in WP Property plugin
