### ISSUE TITLE
some odd message on different actions 

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#153]
in Safari 
![image](https://user-images.githubusercontent.com/5111163/38687540-95cf7118-3e7f-11e8-8a0e-4726af9969c6.png)

![image](https://user-images.githubusercontent.com/5111163/38690121-fc7eacc0-3e85-11e8-9155-f3e8914d6f23.png)

**Comment by SoSeductive** [comment]
@Mashenka 
Need to remove old messages which was added before i fixed issue #42 
Also I added filter for messages on admin page.

**Comment by SoSeductive** [comment]
@Mashenka Already in `latest`
