### ISSUE TITLE
Visualize user data button not working

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#155]
some notes how it should work

You will see graphics for all attributes from your Data tab which have Dropdown or Checkbox Data Input and filled at least in 2 users profiles.

**Comment by SoSeductive** [comment]
@Mashenka This is because `Google Visualization` Feature Flag was disabled `(turned to false)`

**Comment by Mashenka** [comment]
@SoSeductive do not know why. Enable it please for the next release

**Comment by SoSeductive** [comment]
@Mashenka Done. Pushed into latest
