### ISSUE TITLE
Deleteing the system subscriber function.

### ISSUE THREAD

**Issue by Smoot328** [wp-crm/wp-crm#161]
When editing any user data or at least saving click without editing anything, the plugin deletes the system subscriber function. With this, the user can no longer log in to the site.

**Comment by SoSeductive** [comment]
@Smoot328 Can you give me sreenshots? What did you mean `subscriber function` ? How can i repeat this issue?

**Comment by Smoot328** [comment]
@SoSeductive This was an issue submitted by a user. I'm not sure how to repeat the issue of if it is a bug. that's what I would like you to do. Below is the user's exact submission. let me know if this helps.

> I'm using the plugin and noticed a flaw. 
> When editing any user data or at least saving click without editing anything, the plugin deletes the system subscriber function. With this, the user can no longer login to the site. 
> So one way I found to work around this, is every time I edit any given user data, I select the subscriber function again so that the error does not happen. 
> It should be something simple because the plugin simply does not retrieve the user's role that is already registered in the database.

**Comment by SoSeductive** [comment]
@Smoot328 I tried to research plugin, but have no results yet. What did mean - "the plugin deletes the system subscriber function"? What it is "subscriber function"?

**Comment by Smoot328** [comment]
No worries this was an inquiry from a legacy user of our plugin. This was all that was provided and it doesn't seem to be any money attached to this so im closing the issue
