### ISSUE TITLE
The form is vulnerable to a cross site scripting attack

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#42]
We need to sanitize  date before saving using wp_kes or a function of that nature https://codex.wordpress.org/Function_Reference/wp_kses

Step 1. Create a shortcode form that does NOT contain the field created in step 1. 
Step 2. Fill out the form on the client side, entering this as the message <script>alert('xss message');</script> 
Step 3. Return to contact page, javascript is executed! (message pops up)

**Comment by SoSeductive** [comment]
@Mashenka Can you give me list of allowed HTML elements and protocols ?

**Comment by SoSeductive** [comment]
@Mashenka Added allowed HTML elements - `a[title]`, `a[href]`, `br`, `em`, `strong`

**Comment by SoSeductive** [comment]
If issue is resolved - PR https://github.com/wp-crm/wp-crm/pull/145
