### ISSUE TITLE
Show button on admin filter revering to default en translation

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#46]
Step 1. Install wordpress in french. 
Step 2. Load french .mo file. https://poeditor.com/join/project?hash=bcf9852ea63016bd72bb0c7ab1378f55 
Step 3. Interface changes to french for server side code, but when you click “Show”in the filters it switches to hardcode english in the javascript.

Just to be clear this is for the /wp-admin/admin.php?page=wp_crm page
1. Default state, translates correctly. 
2. After clicking "montrer", switches to french. 
3. After closing, permanently stuck on english now, regardless of state.

http://screencast.com/t/x3iY5on30dRn

**Comment by alimuzzaman** [comment]
Now l10n strings from l10n.php file can be used in JavaScript like wpc.strings.key

**Comment by Mashenka** [comment]
Issue still the same - 
![image](https://cloud.githubusercontent.com/assets/5111163/18434502/27e2669c-78f6-11e6-8a87-96a4aafaf36c.png)

I have change language to ru and tried to click Показать, after I click on it, it become en

**Comment by alimuzzaman** [comment]
Did you updated translation file?

**Comment by Mashenka** [comment]
no

**Comment by alimuzzaman** [comment]
That's why not working yet. I have added text in l10n file. You need to translate new added string.

**Comment by Mashenka** [comment]
Anton updated localization file but still reverted to English
here is commit https://github.com/wp-crm/wp-crm/commit/7b6519cb62407b4ae64316a60993d57c6d3e95ae

![image](https://cloud.githubusercontent.com/assets/5111163/18475060/b81991ae-79cd-11e6-977d-300975fb21c4.png)

**Comment by alimuzzaman** [comment]
Sorry for that. I was forgot to say how it work.
It work same as wp property. it use l10n.php save the translated string in uploads\wpc_cache\crm-l10n.js in the selected language. I have added option to clear cache like wp property in help tab. Also cache will be cleared when settings saved.

You need to clear cache from help tab. I have tested on local and it worked.

Cache could be cleared when plugin activated if needed.

**Comment by Mashenka** [comment]
Show now working correctly.

Now Hide(Скрыть) do not appear after I click Show(Показать). It seems that string was deleted cause I do not see it in po file at all.

https://github.com/wp-crm/wp-crm/blob/v1.0/static/languages/wp-crm-ru_RU.po

**Comment by alimuzzaman** [comment]
Why you are checking on v1.0? Shouldn't you check on latest?

**Comment by Mashenka** [comment]
I was checking on workspace. The issue still exist there.

Yes, you are right on latest hide string exist

**Comment by alimuzzaman** [comment]
It's caching on server and not browser. I think there are some sort of caching system in workspace.

**Comment by Mashenka** [comment]
![image](https://cloud.githubusercontent.com/assets/5111163/18665188/b06127d6-7f2e-11e6-99fd-059588320a70.png)
