### ISSUE TITLE
Aftter update of the plugin Splash message shows Warnings

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#55]
Warning: include(Z:\home\wpp-org.loc\www\wp-content\plugins\wp-crm) [function.include]: failed to open stream: Permission denied in Z:\home\wpp-org.loc\www\wp-content\plugins\wp-crm-group-messages\vendor\usabilitydynamics\lib-wp-bootstrap\lib\classes\class-dashboard.php on line 108

Warning: include() [function.include]: Failed opening 'Z:\home\wpp-org.loc\www\wp-content\plugins\wp-crm/' for inclusion (include_path='.;C:\php\pear') in Z:\home\wpp-org.loc\www\wp-content\plugins\wp-crm-group-messages\vendor\usabilitydynamics\lib-wp-bootstrap\lib\classes\class-dashboard.php on line 108

**Comment by antonkorotkov** [comment]
Could not replicate with the latest plugins and add-ons
