### ISSUE TITLE
New option. Minimum user level to manage WP-CRM

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#68]
Like on WP-Invoice - http://screencast.com/t/qi5tTKPT
![image](https://cloud.githubusercontent.com/assets/6744156/18419480/bf06c5dc-787d-11e6-8a8e-84a68dd4846e.png)

**Comment by alimuzzaman** [comment]
What will be under restriction?
Total WP CRM?
or specific 
1. New persion
2. Settings
3. Add-ons

**Comment by Mashenka** [comment]
Total WP-CRM, like WP-Invoice has - http://screencast.com/t/yAF2agq1dq7T
You could also add the same option for Group message add-on(when it activated)
Minimum user level to manage WP-CRM:Group Messages

**Comment by Mashenka** [comment]
can you also add to list of Roles - Agents

**Comment by alimuzzaman** [comment]
Should this block user from using front end form if don't have permission? currently all functionality is being blocked if user don't have required level.

**Comment by Mashenka** [comment]
He shouldn't see just WP-CRM in Sidebar on backend, but  he should have ability to log in if there is such option on the site.

**Comment by Mashenka** [comment]
This shouldn't influence front-end, only backend. 

At the moment I do not see contact form if I'm not logged in

**Comment by Mashenka** [comment]
Agent role should be in the list only when Agents add-on is enabled for WP-Property.

**Comment by Mashenka** [comment]
That option shouldn't allow to chnage roles or passwords in wp-crm profiles, so probably need to add new option under Minimum user level to manage WP-CRM with the name
"Enable Special Actions MetaBox"

![image](https://user-images.githubusercontent.com/5111163/27691789-cc5390a8-5ced-11e7-817b-98ebb30f1117.png)


refference for me - https://usabilitydynamics.uservoice.com/admin/tickets/15848/?q=assignee%3Ame+status%3Aopen
