### ISSUE TITLE
Add ability to attach file to the forms

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#71]
There will be new Input type - File Upload
![image](https://cloud.githubusercontent.com/assets/5111163/18906934/437eca66-8572-11e6-80f4-318f4f97bb62.png)

There also should be security check to avoid downloads of malicious files.

**Comment by ruess** [comment]
Please!!

**Comment by alimuzzaman** [comment]
@Mashenka Review this issue.

**Comment by Mashenka** [comment]
ok,  I saw that in review, just thinking about implementation.

**Comment by Mashenka** [comment]
Also I can't check until this issue will be fixed because contact form no more available when I logged out - https://github.com/wp-crm/wp-crm/issues/68

**Comment by Mashenka** [comment]
where not logged in user should browse his file? - https://workspace.uds.io/crm/
that button is not working

**Comment by Mashenka** [comment]
where not logged in user should browse his file? - https://workspace.uds.io/crm/
that button is not working

Can you make that field looked as attachment

**Comment by Mashenka** [comment]
Did you check the form? I can't submit anything
![image](https://cloud.githubusercontent.com/assets/5111163/20929909/4a0ee512-bbd4-11e6-8c9a-3c1e2eca9b77.png)

**Comment by alimuzzaman** [comment]
For non logged in user if Form method is set to GET it will be POST if there is any file_upload field.

**Comment by Mashenka** [comment]
From one of our user.
 Can you check @alimuzzaman ?

> just to let you know that I've fixed the upload button pb on firefox :

wp_crm_global.js : 139

```
}), jQuery(".wpc_file_upload").on("click", function() { 
replaced by 
}), jQuery(".wpc_file_upload").on("click", function(event) {
```
