### ISSUE TITLE
Logged users not albe to access to wp_crm_my_profile page

### ISSUE THREAD

**Issue by AlesJiranek** [wp-crm/wp-crm#74]
I'm not able to access wp_crm my profile page if I don't have admin role. When I click on profile icon in menu I'm not redirected and I see default wp profile.php even If I have checked to override default profile page. When I manualy type adress `/wp-admin/admin.php?page=wp_crm_my_profile` I get `You do not have sufficient permissions to access this page.` Is it possible that I have something wrong in my configuration or is it bug?

**Comment by Mashenka** [comment]
Hello.

Manage wp-crm can only administrators, this is by design. We can create new option for you as custom service. Contact us using [this form](https://www.usabilitydynamics.com/contact-us/) is you are interested. 

Regards.
