### ISSUE TITLE
Add ability to show WP-CRM on Network admin

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#77]
Notes which were found while Anton tried to troubleshoot that issue:
- CRM  menu not showing on Network admin when activating WP-CRM on all network
- some JS  not including
- Only Super administrator will be shown on the list of ALL people if previous 2 issues will be fixed( and this is wrong)

At the end there should be
- All  People tab and that's all (no need for others)
- and also sidebar filter(backend) with following fields:
1. Site
2. User

**Comment by alimuzzaman** [comment]
@Mashenka Have question about this section.

> and also sidebar filter(backend) with following fields:
> 1. Site
> 2. User

**Comment by Mashenka** [comment]
Call me, I will explain

**Comment by Mashenka** [comment]
* [ ] Fatal error on activation wp-crm
Parse error: syntax error, unexpected '||' (T_BOOLEAN_OR), expecting ')' [closed] in
wp-crm/vendor/usabilitydynamics/lib-wp-bootstrap/lib/classes/class-bootstrap.php in line 595

Incorrectly placed parentheses. 
there should be
 if( empty($_POST['key']) || empty($_POST['slug']) || empty($_POST['type']) || empty($_POST['version']) ) {

* [ ] There is no option to deactivate wp-crm on newtwork at the moment

* [ ] Do not see any of required options.

as before Only super admin in this list
![image](https://cloud.githubusercontent.com/assets/5111163/18913552/0e0a8676-8591-11e6-9820-7e8451839e69.png)

Here you can see that I have more users
![image](https://cloud.githubusercontent.com/assets/5111163/18913522/f22374b8-8590-11e6-9c6b-d06d6ea58766.png)


All tabs there, there should be only All People tab

and default filter there, but there should be Site and User search fields

**Comment by Mashenka** [comment]
when installing on network, at the moment working like on single site

**Comment by alimuzzaman** [comment]
@Mashenka  I can't replicate issue. Please check again.

**Comment by Mashenka** [comment]
![image](https://cloud.githubusercontent.com/assets/5111163/19473074/a8e6cc58-9532-11e6-936c-46cdfe9119ec.png)

**Comment by Mashenka** [comment]
nothing changed
