### ISSUE TITLE
Lookup field

### ISSUE THREAD

**Issue by rods** [wp-crm/wp-crm#78]
Add ability to create a lookup dropdown field using a query or relation

**Comment by Mashenka** [comment]
Hello.

What is the reason you can't use user filter on backend?

Regards.

**Comment by rods** [comment]
Because I would like to connect users and create a hierarchy . Example For a user can be head of another in the same company then at the time of registering users there would be a dropdown with users (based on the query) that have the leading position

**Comment by Mashenka** [comment]
Please leave your idea with detailed instruction here - http://feedback.usabilitydynamics.com/forums/95257-wp-crm

We are using Github for already scheduled tasks.
