### ISSUE TITLE
Add [agent_email] and [author_email] to the list of available tags

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#79]
![image](https://cloud.githubusercontent.com/assets/5111163/18958372/19e21bf0-866b-11e6-9e43-74af35b171fb.png)

**Comment by alimuzzaman** [comment]
I have added text in help tab. Is those tags already working?

**Comment by Mashenka** [comment]
no, you need to add them

**Comment by alimuzzaman** [comment]
Please confirm:
[agent_email] : Email address of assigned agent.
and
[author_email] : Email address of user who created the property.

**Comment by Mashenka** [comment]
yes

**Comment by alimuzzaman** [comment]
If [agent_email] isn't set then it will not replace placeholder.

**Comment by Mashenka** [comment]
Not working for agent [agent_email]
https://workspace.uds.io/property/marias-property/

![image](https://cloud.githubusercontent.com/assets/5111163/19848950/2bf6616e-9f59-11e6-8dcc-02868e23d39a.png)

![image](https://cloud.githubusercontent.com/assets/5111163/19849616/ed7a53b0-9f5c-11e6-9885-477eb60fc8b8.png)

here is typo, need to change
[agent_email] - email address of associate**d** agent.

**Comment by Mashenka** [comment]
still not working. I have assigned  me to this property and set up form with [aget_email]
Still not sending
https://workspace.uds.io/wp-admin/post.php?post=747053&action=edit

**Comment by Mashenka** [comment]
Actually now any message are not coming from wp-crm at all

**Comment by alimuzzaman** [comment]
wpautop() is causing the issue.

**Comment by alimuzzaman** [comment]
WP_CRM_F::minify_js($content); did the trick.

**Comment by Mashenka** [comment]
ok, now messages from wp-crm are sending in general , but not for [agent_email] and [author_email] 
https://workspace.uds.io/wp-admin/post.php?post=747053&action=edit&lang=en
 
[agent_email] not working **probably** of this option, just assumption
![image](https://cloud.githubusercontent.com/assets/5111163/21008987/f26fa8d0-bd4c-11e6-90d0-f565144bb33e.png)

**Comment by Mashenka** [comment]
great. finally working
