### ISSUE TITLE
messages on network

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#84]
messages  are showing on all sites from network (need to check when https://github.com/wp-crm/wp-crm/issues/83 will be fixed)

![image](https://cloud.githubusercontent.com/assets/5111163/21268315/e2e38448-c3b6-11e6-859a-38e175d6905e.png)

**Comment by Mashenka** [comment]
Now  messages do not appear there at all

**Comment by alimuzzaman** [comment]
@Mashenka It's worked on my local.

**Comment by Mashenka** [comment]
checking again

**Comment by alimuzzaman** [comment]
@Mashenka make sure you have the Message box on form.

**Comment by Mashenka** [comment]
Network. When I logged in messages are not saving. When I logged out they do.

![image](https://cloud.githubusercontent.com/assets/5111163/24545925/e25e2ade-1611-11e7-8380-e1ed58c3c06f.png)

![image](https://cloud.githubusercontent.com/assets/5111163/24545950/f7d3a36c-1611-11e7-8e67-d286dc52a844.png)

**Comment by alimuzzaman** [comment]
@pemaxim @antonkorotkov Help needed.
I have added class-upgrade.php to wp crm from wp-property. But seems not firing WPC_Bootstrap::run_upgrade_process() .
https://github.com/wp-crm/wp-crm/blob/develop-alim/lib/classes/class-WPC_Bootstrap.php#L225
https://github.com/wp-crm/wp-crm/blob/develop-alim/lib/classes/class-upgrade.php

if I remove this line the fire every time but not sure why don't fire when it's exists. ( https://github.com/wp-crm/wp-crm/blob/develop-alim/vendor/usabilitydynamics/lib-wp-bootstrap/lib/classes/class-bootstrap.php#L218 )

**Comment by antonkorotkov** [comment]
@alimuzzaman I don't know what logic is there. I think you have to debug.

**Comment by alimuzzaman** [comment]
Thanks @antonkorotkov I will debug again.

**Comment by Mashenka** [comment]
this from local

![image](https://cloud.githubusercontent.com/assets/5111163/25280794/de63d0f2-26b3-11e7-929a-845b52bef945.png)
![image](https://cloud.githubusercontent.com/assets/5111163/25281040/bac459ae-26b4-11e7-934d-2a7b6b79fff4.png)

this is from workspace - 
![image](https://cloud.githubusercontent.com/assets/5111163/25282628/b82b1e08-26b9-11e7-8c0f-4c7f95403214.png)

![image](https://cloud.githubusercontent.com/assets/5111163/25282681/e6d0348c-26b9-11e7-85a2-7013eecc6d38.png)


Note, that notification to my mail box is coming
![image](https://cloud.githubusercontent.com/assets/5111163/25283442/767a3176-26bc-11e7-946d-6b7d763c3168.png)
