### ISSUE TITLE
Add google validation in wp-crm forms like an option

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#87]
![image](https://cloud.githubusercontent.com/assets/5111163/21775334/5463cade-d69e-11e6-9434-de44195b9e98.png)

**Comment by alimuzzaman** [comment]
https://usabilitydynamics-sandbox-uds-io-develop-alim.c.rabbit.ci/?page_id=39

**Comment by Mashenka** [comment]
where I can see option for that, how that can be enabled?

**Comment by alimuzzaman** [comment]
In the settings page, Shortcode section. You will find it with other attributes.

**Comment by Mashenka** [comment]
Where users should take these keys?, can you add explanation in Help tab
![image](https://cloud.githubusercontent.com/assets/5111163/22205848/443c00ca-e181-11e6-98f7-9dec4c227dfe.png)

**Comment by Mashenka** [comment]
Also why I do no see that on workspace?

**Comment by alimuzzaman** [comment]
Because it's in another branch than latest. I will create pull request after it's done. So latest will be little clean.

**Comment by Mashenka** [comment]
what about my other question https://github.com/wp-crm/wp-crm/issues/87#issuecomment-274488687

**Comment by Mashenka** [comment]
Captcha is overshadows message
 "Thank you" your message was sent
![image](https://cloud.githubusercontent.com/assets/5111163/23031792/ebf681a8-f47a-11e6-920c-3c88cd2f337d.png)

**Comment by alimuzzaman** [comment]
What was the theme used?

**Comment by Mashenka** [comment]
it seems that Denali issue only

**Comment by Mashenka** [comment]
@alimuzzaman can you fix that for Denali?

**Comment by Mashenka** [comment]
@alimuzzaman Denali styles fixed. Your commit didn't help. https://workspace.uds.io/crm/

**Comment by alimuzzaman** [comment]
@Mashenka You didn't merge the pull request.
[pull/101](https://github.com/wp-crm/wp-crm/pull/101)
