### ISSUE TITLE
JS error Uncaught TypeError: params.append is not a function

### ISSUE THREAD

**Issue by Mashenka** [wp-crm/wp-crm#89]
You can check it here: (fill the form)
https://www.klugscheissen.com/registrieren/

**Comment by alimuzzaman** [comment]
That's not latest. I did commit after that.

**Comment by Mashenka** [comment]
can you show me where did you fix that, I will send to user

**Comment by felipeelia** [comment]
Same error here. I've solved it temporarily changing `lib/class_contact_messages.php` (line 883) from:
`params.append('crm_action', crm_action);`
to
`params += '&crm_action=' + crm_action;`
Did you solve it this way too, @alimuzzaman, or there is another solution?

**Comment by alimuzzaman** [comment]
@EliaBR No, Fix is [here](https://github.com/wp-crm/wp-crm/blob/latest/lib/class_contact_messages.php#L944-L949).
 `params.append` is required when you are using image upload, what uses POST request.

**Comment by felipeelia** [comment]
Nice @alimuzzaman, thanks. I've downloaded it from the WP Plugin Directory and, of course, it's is different from there, sorry.
